vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    imageProfil:
        uri_prefix: /images/imageProfil
        upload_destination: '%kernel.project_dir%/public/images/imageProfil'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
